### ISSUE TITLE
Demo returns error when adding to cart

### ISSUE THREAD

**Issue by robinmetral** [parmsang/gatsby-starter-ecommerce#11]
On for example [this product page](https://parmsang.github.io/gatsby-starter-ecommerce/product/9eda5ba0-4f4a-4074-8547-ccb05d1b5981/), I get:

![screenshot_2018-11-22 crown](https://user-images.githubusercontent.com/35560568/48875345-1d74d300-ee2b-11e8-8445-638ed4139543.png)

Can you reproduce it? Do you know what went wrong? There is no error message in the console.

**Comment by parmsang** [comment]
Apologises for the delayed response....I've been on a long break. 

I've updated the site and fixed this issue. It appears to have been an issue with the Moltin api...That product no longer is listed as part of their demo.
I've upgraded to Gatsby v2 (Gatsby v1 is still available in branch gatsby-v1).

**Comment by robinmetral** [comment]
Thanks for the update @parmsang! All good :slightly_smiling_face:
