### ISSUE TITLE
Checkout fails after payment

### ISSUE THREAD

**Issue by shendriksza** [parmsang/gatsby-starter-ecommerce#13]
After going through the checkout procedure,  the payment succeeds and I get returned to the cart page with nothing changed. The cart still has items and the order does not reflect on Moltin dashboard.

Console shows the following:
`Failed to load resource: the server responded with a status of 400 ()`
on the api call
`https://api.moltin.com/v2/carts/3d8ccdec1a610ec0cc5d5649090270ab/checkout`

I'm sure my Moltin api key is setup correctly as I can register a new customer and that does reflect on the Moltin dashboard.

**Comment by parmsang** [comment]
Thanks for pointing this out. I've made a fix.

**Comment by shendriksza** [comment]
Thank you for giving this issue attention.

I have tried again with the latest commit but the same issue still persists. I will try debugging and notify you if I find the problem

**Comment by shendriksza** [comment]
I realised my new error is unrelated to the first one, so thank you Parmsang for fixing the initial bug. I was able to finally complete an orde now by changing the following

The Stripe checkout splits the "Name" field entered with a space character into a first_name and last_name. If a dummy name is entered without a space, the API call to Moltin fails because last_name is null. It will also fail because "county" field is sent as null even though it's not part of the checkout. Using a dummy value in cart.js will finally let me successfully place an order

Thereafter the payment of the order will fail because the response for the API call to checkout returns the order id as "id" and not as "orderId" as is attempted in cart.js.

Once that is fixed, an order can successfully be placed as well as paid for.

There is another issue (Max stack call size exceeded) when viewing "My Account" page when logged in. I am investigating now but I suspect another issue with the Moltin API call attempting to get returned orders and displaying them in myaccount.js

**Comment by shendriksza** [comment]
The stack size exceeded was a react-helmet issue. Updating to react-helmet 6.0.0-beta and fixing the import in SEO/index.js (`import {Helmet} from "react-helmet"`) solved it

**Comment by parmsang** [comment]
Thank you Shendriksza for alerting me to these issues and for your detailed feedback. I have fixed the issues identified. I was able to successfully place an order in test mode.

Just a note, make sure to reset local storage (specific to Moltin) prior to running npm run develop as I've found this can cause some issues too.

Also note that I deliberately chose to fetch cart count from local storage just to keep things simple and more performant, but you can update the code to fetch cart items using the Moltin API in the CartProvider.
