### ISSUE TITLE
Customer password reset?

### ISSUE THREAD

**Issue by simpleshadow** [parmsang/gatsby-starter-ecommerce#15]
How would a customer reset their password (if forgotten) via Moltin? 

I don't see anything in the [Moltin docs](https://docs.moltin.com/orders-and-customers/customers) about this. 

(This project is amazing @parmsang! Thanks for creating and sharing.)

**Comment by shendriksza** [comment]
From what I've seen, the only way is to override users password on the Moltin dashboard with a new one

**Comment by notrab** [comment]
Hi @simpleshadow  @shendriksza 

We currently don't handle any of the business logic required for resetting customer passwords, however you can make use of `client_credentials` authentication type to reset passwords within your server/serverless functions.

https://docs.moltin.com/orders-and-customers/customers/update-a-customer should be more helpful 😉
