### ISSUE TITLE
TypeError: Cannot read property 'allMoltinProduct' of undefined

### ISSUE THREAD

**Issue by karademada** [parmsang/gatsby-starter-ecommerce#16]
Hello, 

i faced an issue with the plugin, i haved created a .env.development with the MOLTIN_CLIENT_ID=
STRIPE_PUBLISHABLE_KEY=
when i logged the MOLTIN_CLIENT_ID is ok, but the allMoltinProduct query is failed, and when i inspect the documentation, i did not find the allMoltinProduct.

does anyone got this? it's just do a npm run develop after running the cli.

regards

**Comment by owii03** [comment]
same here. I got the same issue.
<img width="897" alt="Screen Shot 2019-04-20 at 3 50 06 AM" src="https://user-images.githubusercontent.com/38784896/56443556-691aa280-631f-11e9-9c4d-a5246c667b7d.png">

**Comment by bahoffman** [comment]
same issue

**Comment by gurjmatharu** [comment]
+1

**Comment by amdolan** [comment]
You'll need to add a product to your Motlin catalogue, I think.  I am still working through errors in getting this to run, as I don't have the custom properties defined on my products.   e.g.

```
material
max_watt
bulb
bulb_qty
```

`see src/templates/ProductPage.js`

I wonder if I missed something regarding creating product properties.

**Comment by hella453** [comment]
@amdolan have you managed to figure it out?

**Comment by Jeerjmin** [comment]
Need to change status of product to 'live'

**Comment by parmsang** [comment]
It's been fixed. 
The issue was that Moltin, who provide the backend api and the content for the demo lamp store, had revised this content and the structure of the content returned. This was breaking the build.
