### ISSUE TITLE
Error with fresh install

### ISSUE THREAD

**Issue by jacintocapote** [parmsang/gatsby-starter-ecommerce#21]
I'm  trying to start a fresh install for checking but I'm getting:

error UNHANDLED REJECTION

 ```
 TypeError: Cannot destructure property `link` of 'undefined' or 'null'.

  - gatsby-node.js:30 processProduct
    [gatsby-store]/[@moltin]/gatsby-source-moltin/gatsby-node.js:30:25

  - gatsby-node.js:166 products.forEach
    [gatsby-store]/[@moltin]/gatsby-source-moltin/gatsby-node.js:166:15

  - Array.forEach

  - gatsby-node.js:164 createProducts
    [gatsby-store]/[@moltin]/gatsby-source-moltin/gatsby-node.js:164:14

  - gatsby-node.js:177 Object.exports.sourceNodes
    [gatsby-store]/[@moltin]/gatsby-source-moltin/gatsby-node.js:177:9

  - task_queues.js:86 processTicksAndRejections
    internal/process/task_queues.js:86:5
```

**Comment by jacintocapote** [comment]
Looks like I need add a token id should be good to add to documentation this step is before launch the server.

**Comment by devconxol** [comment]
Please, how do you solve it. I have the same issue

**Comment by elijahio** [comment]
Would the Token ID field go into `.env.development`? I am also getting this error.

**Comment by Jeerjmin** [comment]
I get same error 
`Unknown field 'allMoltinProduct' on type 'Query'. Source: document `IndexQuery` file: `GraphQL request`
`
It is starter or not ?

**Comment by daljeetvirdi** [comment]
I get same error

```Unknown field 'allMoltinProduct' on type 'Query'. Source: document IndexQuery file: `GraphQL request```

**Comment by IsaacCDHall** [comment]
I had the same error, updated all packages in npm, ran an audit fix and now im receiving two GraphQL errors `- Unknown field 'background_colour' on type 'MoltinProduct!'. Source: document `IndexQuery` file: `GraphQL request`
  
  GraphQL request:14:13
  13 |             description
  14 |             background_colour
     |             ^
  15 |             new
- Unknown field 'mainImageHref' on type 'MoltinProduct!'.`

**Comment by FelixFreelancer** [comment]
Same here. 
I can't execute this project. 
how can we see it?

**Comment by parmsang** [comment]
Hi guys - I've been on a long break but hopefully plan to fix outstanding issues this weekend. Apologises for not responding sooner. 

Note that the main issue appears to be that Moltin, who provide the backend api and the content for the demo lamp store, have revised this content and the structure of the content returned. I will need to update the code to adapt to these recent, and I have to say, unexpected changes.

**Comment by parmsang** [comment]
I have updated the project and this issue should be fixed.

**Comment by elijah-io** [comment]
Thanks so much, @parmsang – fresh install works well now, so I recommend closing this issue.

I did run into another issue that I assume has to do with how my moltin test product is configured; do you know what this might be?

<img width="1024" alt="Screen Shot 2019-08-31 at 11 07 18 AM" src="https://user-images.githubusercontent.com/22265271/64066464-a2252680-cbdf-11e9-9843-78553cb9ee10.png">

If I remove that query, I just get another similar error to do with 'material' being undefined.

**Comment by parmsang** [comment]
Thanks for the kind words @elijah-io ,

That's very likely because no background colour property is set for your products in your personal Moltin store, unlike the lamp store used for this starter. I suggest reviewing the response you get back using graphiql and using that response as the foundation to build your e-commerce site. As a quick fix you can simply delete the few references to background_colour (and other unused properties such as material etc) in the code.

Alternatively, you can set these properties (background colour. material etc) for your personal products via the Moltin site.

**Comment by elijah-io** [comment]
Thanks so much for pointing me in the right direction, for fixing the issue, and above all, for building this project. You rock!

**Comment by marksteven** [comment]
Sept 2020
Same issue 
Any ideas on what causes this?

GraphQL Error Encountered 2 error(s):
- Unknown field 'mainImageHref' on type 'MoltinProduct!'. Source: document `IndexQuery` file: `GraphQL request`
  
  GraphQL request:14:13
  13 |             description
  14 |             mainImageHref
     |             ^
  15 |             meta {
- Unknown field 'mainImageHref' on type 'MoltinProduct!'.

      file: /Users/mark/Documents/sites/gatsby-starter-ecommerce/src/templates/ProductPage.js
