### ISSUE TITLE
Customer Sign In

### ISSUE THREAD

**Issue by marquez138** [parmsang/gatsby-starter-ecommerce#23]
Hi any reason why I get "Sorry Cannot register at this time." error when i do a test sign up? Thanks

**Comment by parmsang** [comment]
I am aware of this issue. There is nothing wrong with the code. The issue stems from Moltin, unexpectedly, making changes to the backend datasource used for this demo. I have been in contact with Moltin and hopefully we will see a fix soon.

**Comment by marquez138** [comment]
roger that thanks for the quick reply

**Comment by marquez138** [comment]
Not an issue on my project closing
