### ISSUE TITLE
Stripe react elements

### ISSUE THREAD

**Issue by marquez138** [parmsang/gatsby-starter-ecommerce#24]
Hi i was hoping to use stripes react elements to change the checkout flow and style similar to moltins demo  <a href="url">here</a>. I was hoping you could point me in the right direction as to which files i needed to edit or replace in order to add to this current project. Any help would be greatly appreciated. Thanks again

**Comment by parmsang** [comment]
Hi - apologises for the delay responding, I recently returned from a holiday. I just updated the site to use the new Moltin datasource, as previously discussed [here](https://github.com/parmsang/gatsby-starter-ecommerce/issues/23). This fixes a number of outstanding issues. 
You have linked this store, but I think you meant this [demo](https://github.com/moltin/gatsby-demo-store). 
It uses react-stripe-elements and is used in conjunction with [gatsby-plugin-stripe](https://www.gatsbyjs.org/packages/gatsby-plugin-stripe/). Key files to update are [wrap-with-provider](https://github.com/parmsang/gatsby-starter-ecommerce/blob/master/wrap-with-provider.js) and [CartSummary](https://github.com/parmsang/gatsby-starter-ecommerce/blob/master/src/components/CartSummary/index.js). Pull requests are welcome....or I may update to use stripes react elements next weekend when I should have more free time.

**Comment by parmsang** [comment]
There has been no further update on this issue so I'm going to close it.
I had a look at react-stripe-elements, and while it is excellent, I'm reluctant to use it for this _starter_ . I'd like to keep the starter as simple as possible, where it serves as a springboard for users to add additional functionality/complexity, such as react-stripe-elements.
