### ISSUE TITLE
Duplicated documents error

### ISSUE THREAD

**Issue by Dejulia489** [parmsang/gatsby-starter-ecommerce#26]
This is the error I received out of the box. 

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents: - ProductsQuery - IndexQuery

**Comment by parmsang** [comment]
I am aware of this issue. There is nothing wrong with the code. The issue stems from Moltin, unexpectedly, making changes to the backend datasource used for this demo. I have been in contact with Moltin and there will be a fix soon. I am currently taking a holiday and intend to work on the starter next weekend when I return..

**Comment by Dejulia489** [comment]
Thank you for the update. The demo looks great by the way.

**Comment by parmsang** [comment]
I have made several fixes and the demo now uses the new Moltin datasource. You will notice content looks a bit different, some new nice looking lamps, with some minor features removed but essentially the same as before.
