### ISSUE TITLE
moltin.com - questions....

### ISSUE THREAD

**Issue by mrhut10** [parmsang/gatsby-starter-ecommerce#3]
I like the look of this project, however I've spent half hour looking through https://moltin.com trying to find pricing and haven't had any luck at all.

Are you aware of documentation of pricing tiers / models.

Thank you in advanced

**Comment by mrhut10** [comment]
Than you, really appreciate it...

**Comment by parmsang** [comment]
Moltin advise that they currently tailor their pricing specific to user requirements. They suggest that you contact them directly to learn more.

**Comment by mrhut10** [comment]
Thank toy for following up.
From there point of view that's disappointing not having transparent pricing / business model.

**Comment by mrhut10** [comment]
Makes me think something like snipcart would be a better alternative in the future.

**Comment by parmsang** [comment]
I'm surprised too that they are not so transparent with their pricing. Until recently they were.

I would still encourage you to contact them because their product is excellent.

**Comment by mrhut10** [comment]
mmmm ok, I'll message them tomorrow.
manly as i'd loved to try your product, although does make me uncomfortable dealing with people that aren't transparent.

i'll let you know how I go, and hopefully get to have a play with your project after that

:) thank you @parmsang

**Comment by markdowney** [comment]
See this thread for my experience regarding pricing: https://forum.moltin.com/t/pricing/961/24
In short, I add to move off Moltin and transition to Shopify.
I'd recommend re-opening this issue open until they figure out their pricing strategy to hopefully save some people some time.
