### ISSUE TITLE
Install fails due to Cypress checksum mismatch

### ISSUE THREAD

**Issue by mathiscode** [parmsang/gatsby-starter-ecommerce#34]
When performing a clean `gatsby new mystore https://github.com/parmsang/gatsby-starter-ecommerce`, I get the following error:

```
[4/4] Building fresh packages...
[-/17] ⠈ waiting...
[-/17] ⠈ waiting...
[-/17] ⠈ waiting...
[13/17] ⠈ cypress
error F:\Code\mystore\node_modules\@types\testing-library__cypress\node_modules\cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: F:\Code\mystore\node_modules\@types\testing-library__cypress\node_modules\cypress
Output:
Installing Cypress (version: 4.5.0)
```

...

```
[18:15:18]  Downloading Cypress      99% 3s [title changed]
[18:15:20]  Downloading Cypress      100% 0s [title changed]
[18:15:21]  Downloading Cypress      100% 0s [failed]
[18:15:21] → The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration     

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.5.0?platform=win32&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 209c4108757f734812b133cd06658169ca37ba8cc58ff94506f84bf0493f1e8b5e2c972f9dbd3be91bc43fe0bddbe8fad00d800440375ba4c1a1c5d073a6a81a
Computed checksum: 98916ddb62e663d539d9b6f500995ea799ae32bae6a9d99ce62b1ac1eca62fa9d4c3e35ac79bcb91d82c22f7e73f9e3ebff2f3d9d3b0311ed281e766cfbaa914

Expected downloaded file to have size: 170413429
Computed size: 170413429
```

I am using Git Bash on Windows 10 Pro x64. I've tried multiple times, and I made sure my network was performing normally.

Let me know if there are other details I can provide that may help. Thanks!

**Comment by parmsang** [comment]
Hi!

I suspect it's related to [this](https://docs.cypress.io/guides/references/proxy-configuration.html#Set-a-proxy-on-Linux-or-macOS). 

Note that you don't need Cypress to get the app running so just remove it from package.json.

**Comment by mathiscode** [comment]
> 
> 
> Hi!
> 
> I suspect it's related to [this](https://docs.cypress.io/guides/references/proxy-configuration.html#Set-a-proxy-on-Linux-or-macOS).
> 
> Note that you don't need Cypress to get the app running so just remove it from package.json.

Thanks! I don't need or use a proxy so it's still odd that it would be failing, but if it's not needed to get up and running, then I'll just remove it.

Keep up the great work!
