### ISSUE TITLE
Add copyright notice to license

### ISSUE THREAD

**Issue by balibebas** [parmsang/gatsby-starter-ecommerce#37]
This is a great starter but as it stands the work added to the gatsby starter is unclear from a licensing perspective given no copyright notice was added by the author. Please add a copyright notice. For more information see: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html. If you're unsure how to add a notice let me know and I'll help. Note Gatsby recently relicensed all their starters under 0BSD.

**Comment by parmsang** [comment]
Hi @balibebas - Thanks for notifying me. If you can help that is much appreciated.

**Comment by balibebas** [comment]
Sure bud. Basically you have two options. Rebase on a starter following the transition to 0BSD and you can do whatever you want with the license. Option 2 and less work is to add a copyright notice (mentioned with example in Mitchell's post) with your authorship info (you can use a pseudonym if you like but you need to add something otherwise licensure is unclear).

If you decide to go for door 1 you can use whatever license you like and will not have to carry the MIT license around. The choice of liceses is up to you though for the sake of your users I'd stick with MIT given it's what they were expeecting when they started using this product.

For a specific examples of how to update the license please see: https://github.com/AlexanderProd/gatsby-shopify-starter/commit/1e2cc6e2e145077ded3a1e9e2d32141d363ad131

**Comment by parmsang** [comment]
@balibebas Thank you for taking the time to make me aware of this update and advising me of the necessary changes. Very much appreciate it.  👍
