### ISSUE TITLE
Moltin E-Commerce API

### ISSUE THREAD

**Issue by manpenaloza** [parmsang/gatsby-starter-ecommerce#43]
Hey,
thx for making this starter!

As I like how this starter is built and how it works, I wanted to use it. As it requires a Moltin account, I tried to organize one. As Moltin was acquired by Elasticpath, Moltin does not exist anymore. Do you know whether this also works with the Elasticpath version?

Business-related:
As it's very difficult to find our pricing details of Elasticpath, a sales representative of Elasticpath wrote to me, that that the entry-level starts at 50k/year (?!?!). Did he tell me just "anything" or does anyone have other/cheaper Elasticpath options?

Thx for feedback!

**Comment by jonnysmillie** [comment]
I have had similar issues with Elastic Path. Probably better to use Snipcart or some other open CMS such as Strapi.

**Comment by marksteven** [comment]
I've had start up issues on fresh install.
What did you do to fix this please?

I get this 
GraphQL Error Encountered 2 error(s):
- Unknown field 'mainImageHref' on type 'MoltinProduct!'. Source: document `IndexQuery` file: `GraphQL request`
  
  GraphQL request:14:13
  13 |             description
  14 |             mainImageHref
     |             ^
  15 |             meta {
- Unknown field 'mainImageHref' on type 'MoltinProduct!'.

      file: /Users/marksteven/Documents/sites/gatsby-starter-ecommerce/src/templates/ProductPage.js

**Comment by parmsang** [comment]
@marksteven - see [here](https://github.com/parmsang/gatsby-starter-ecommerce/issues/45#issuecomment-754202378).
