### ISSUE TITLE
Netlify template from repo does not build

### ISSUE THREAD

**Issue by andrewdefries** [parmsang/gatsby-starter-ecommerce#45]
Hello, great demo. I tried to deploy the Netlify template via this link:

https://templates.netlify.com/template/gatsby-starter-ecommerce/

But it does not build. Is this because you have specified build settings specific to hosting on github.io rather than netflify?

**Comment by parmsang** [comment]
Hi there - there was an issue with the Moltin/Elastic-Path source plugin. I've updated some of the packages and things should work now.

**Comment by andrewdefries** [comment]
Hello parmasang, again really impressive demo. I like the simple layout and it comes through really well on mobile. 

I can confirm your changes have debugged the netlify deploy:

https://agitated-mcclintock-fb0138.netlify.app/

Do you have any suggestions on how to manage the back end of this ecommerce store such as the products? Is snipcart enough for this?

Thank you
