### ISSUE TITLE
npm ERR! code E401 npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

### ISSUE THREAD

**Issue by esportleague** [parmsang/gatsby-starter-ecommerce#47]
I'm not sure if it's a self authentication problem or not. First of all motlin is not free anymore so I have no way to check . can I somehow bypass this and not live with this solution ??

**Comment by pcktlwyrcode** [comment]
concur just got the same. Mac M Chip Big Sur

**Comment by pcktlwyrcode** [comment]
Concur.. looking for a workaround

**Comment by parmsang** [comment]
Seems to be working fine for me now.

**Comment by hashiromer** [comment]
I am getting the same error

**Comment by parmsang** [comment]
@hashiromer Can you tell me what version of node and npm you are using?

**Comment by royabhishek** [comment]
i am getting the same error
node version: v15.11.0
npm version: 7.6.3

**Comment by parmsang** [comment]
@royabhishek - Thanks for the feedback. I believe this issue is now fixed.

**Comment by pragati0416** [comment]
Hi,
I'm also experiencing the same error.I have tried to find out solution but nothing worked for me.
I'm using below node and npm versions:-
node ----> v16.15.0
npm ----->8.5.5

**Comment by parmsang** [comment]
I closed this a while back. Did you pull latest changes and reinstall everything? Sorry to ask this but I suspect this might be the issue?

**Comment by pragati0416** [comment]
yes I have reinstalled everything but still I'm facing issue

**Comment by pragati0416** [comment]
I have done reinstallation and everything working fine.
Thanks

**Comment by pst37** [comment]
Hey @parmsang ,I am facing the same issue on  different repo, if you could help me with steps , it will be great.
