### ISSUE TITLE
Hello There! I am Completely new to JAMstack

### ISSUE THREAD

**Issue by wredmansola** [parmsang/gatsby-starter-ecommerce#48]
I deployed this repo directly with netlify. Now I don't know anything. I mean that, I want to add products on my site and get payments from stripe to my Stripe account. similarly to add products I am unable to login to my admin panel. Please help here. I want to live this site for my project.

**Comment by parmsang** [comment]
This demo is using [elasticpath ](https://www.elasticpath.com/) (previously Moltin) to fetch data to build the site. You will need to have an account with them (follow their tutorials) or an alternative provider to get data specific to your own store and make the necessary changes to the code to suit your products as required.
