### ISSUE TITLE
Upgrade to Gatsby 2.0?

### ISSUE THREAD

**Issue by SilverHazeLazers** [parmsang/gatsby-starter-ecommerce#6]
Thanks @parmsang for your work on this starter.

Just wondering if you are intending to update this starter to Gatsby v2 (latest release is gatsby@2.0.0-rc.15 ). 

I had a go myself using the '[Migrating from v1 to v2](https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/)' notes but didnt have any luck.

**Comment by parmsang** [comment]
Hi @SilverHazeLazers 

I am quite busy right now and have no immediate plans but if I get the time I'll update it to Gatsby V2.

**Comment by SilverHazeLazers** [comment]
Thanks @parmsang , appreciate the reply

No worries, completely understand. If I have any luck doing so myself I will create a PR

All the best
