### ISSUE TITLE
After switching the Moltin api key I get an error

### ISSUE THREAD

**Issue by jonnysmillie** [parmsang/gatsby-starter-ecommerce#7]
Hi, thanks so much for open sourcing this project. It really is great and I can't wait to get going with it.

Upon switching the Moltin API however I get an error in the browser

<img width="1104" alt="screenshot 2018-09-13 10 21 25" src="https://user-images.githubusercontent.com/7614348/45479688-13ee3100-b73f-11e8-8f51-b0bc0202c8c0.png">

I'm wondering if this is because my Moltin products aren't the same structure as the ones used in the demo? Would it be possible to see the structure of the products used in the demo to compare? Or has anyone else had a similar issue to this? I haven't changed anything other than created the .env file at root with my own Moltin api key.

**Comment by jonnysmillie** [comment]
I actually also changed the Moltin api reference in **gatsby.config**

**Comment by parmsang** [comment]
I've made a small update/fix to the project around environmental variables, however I suspect this may be an issue with the Moltin backend and your product structure as you've suggested. You could console log what is getting returned from Moltin (see the gatsby-source-moltin plugin) and compare to the example project.

Note that I removed products without a main image (for obvious reasons) however you may choose to include these products for your own store and update the code accordingly.
