### ISSUE TITLE
Is update token function correct to load 'mcart'

### ISSUE THREAD

**Issue by efleurine** [parmsang/gatsby-starter-ecommerce#8]
https://github.com/parmsang/gatsby-starter-ecommerce/blob/f825048bbb8204890734e08567401d53e06cdfdc/src/components/Context/AuthProvider.js#L10

It seems that we are loading the cartId instead of the newly received token in the Context Provider.

**Comment by efleurine** [comment]
I created a pull request to fix it #9

**Comment by parmsang** [comment]
merged
